CLASS zbp_r_purinforecordheader DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_purinforecordheader.
  PUBLIC SECTION.
ENDCLASS.



CLASS ZBP_R_PURINFORECORDHEADER IMPLEMENTATION.
ENDCLASS.
