CLASS zbp_r_agencypurchasing DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zr_agencypurchasing.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_R_AGENCYPURCHASING IMPLEMENTATION.
ENDCLASS.
