CLASS zbp_r_productionversion DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_productionversion .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_R_PRODUCTIONVERSION IMPLEMENTATION.
ENDCLASS.
