CLASS zbp_r_emailmasterupload DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_emailmasterupload .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_R_EMAILMASTERUPLOAD IMPLEMENTATION.
ENDCLASS.
