CLASS zbp_r_ledplannedordercomponent DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zr_ledplannedordercomponent.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_R_LEDPLANNEDORDERCOMPONENT IMPLEMENTATION.
ENDCLASS.
