CLASS zbp_r_ledproductionversion DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_ledproductionversion .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_R_LEDPRODUCTIONVERSION IMPLEMENTATION.
ENDCLASS.
