CLASS zbp_r_materialrequisition DEFINITION
PUBLIC
ABSTRACT
FINAL
FOR BEHAVIOR OF zr_materialrequisition.

  PUBLIC SECTION.
    CLASS-DATA mapped_material_document TYPE RESPONSE FOR MAPPED i_materialdocumenttp.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS ZBP_R_MATERIALREQUISITION IMPLEMENTATION.
ENDCLASS.
