CLASS zbp_r_routingupload DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_routingupload .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_R_ROUTINGUPLOAD IMPLEMENTATION.
ENDCLASS.
